---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: yes
  apt:
    upgrade: "yes"
  
- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "install node and npm"
  become: yes
  apt:
    name: ["nodejs", "npm", "libcap2-bin"]
    state: latest
    update_cache: yes

- name: "give safe permission to use port 80"
  become: yes
  shell: |
    setcap cap_net_bind_service=+ep `readlink -f \`which node\``

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present