---
- name: "create directory in remote server"
  become: yes
  file:
    path: /etc/autodeploy
    state: directory

- name: "copy the back end files"
  become: yes
  unarchive:
    src: backend.tar.gz
    dest: /etc/autodeploy

- name: "install dependencies"
  become: yes
  shell:
    cmd: npm install
    chdir: /etc/autodeploy

- name: "build backend"
  become: yes
  shell:
    cmd: npm run build
    chdir: /etc/autodeploy

- name: start app
  become: yes
  shell: |
    cd /etc/autodeploy/
    npm install
    pm2 stop default
    pm2 start npm -- start
    cd dist
    pm2 start main.js --update-env
